name: calculator_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

flutter:
  uses-material-design: true

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.6.0

dev_dependencies:
  lints: ^5.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
